  
server:
  port: 8090
 
spring:
  application:
    name: three-service  

  datasource:
    url: jdbc:h2:mem:tokendb
    username: sa
    password: password
  sql:
    init:
      mode: always
      
   
      
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect